### ISSUE TITLE
[Feature Request] Corp statistic page, Group members by alts

### ISSUE THREAD

**Issue by AncientD** [ppfeufer/allianceauth-afat#246]
### Context

Would you add grouped by alts, like prev portal, that really helps to calculate attendance.

### Additional context

https://i.imgur.com/6YsMP8m.png

**Comment by ppfeufer** [comment]
What is "prev portal"?

And please use an image hoster that is not infested with trackers and ominous JavaScript. Imgur is blocked in my network for precisely that reason.

**Comment by ppfeufer** [comment]
You do realise that I don't have access to that website, right? And I'm not even trying to log in with all the excessive ESI scopes it wants to have to even check.

But as said in your other feature request, the statistics pages are on my list to be redone at some point, so this might be a thing in the future.

**Comment by AncientD** [comment]
Yeah, but you can see group by alts what i talking about on screenshot

**Comment by ppfeufer** [comment]
Delivered with v3.5.0

![image](https://github.com/user-attachments/assets/c3f7838f-a7c7-45f5-8f19-546c5774cdfa)
