### ISSUE TITLE
FATs by Weekday for Corp are off by one day

### ISSUE THREAD

**Issue by zmsMarc** [ppfeufer/allianceauth-afat#251]
### Bug Description

Viewing the graph for FATs by Weekday for corp shows the Fats to be one day in the future. FATs that were added on Friday are shown for saturday. Currently it already shows FATs for sunday, eventhough its still saturday march 04.

I assume the graph is supposed to start the week on a sunday instead of monday, and therefore the labels are 1 day off

### Steps to Reproduce

Get FATs at start of month, open graph, see they are tomorrow.

<url>/fleet-activity-tracking/statistics/corporation/<corpID>/2023/3/

### Expected behavior
FATs graph should show correct weekdays

### Screenshots
![grafik](https://user-images.githubusercontent.com/9104198/222890188-e98be9c8-66b4-447f-9660-a62fa677f784.png)

**Comment by ppfeufer** [comment]
Nice find, will be fixed with the next release.

**Comment by zmsMarc** [comment]
![grafik](https://user-images.githubusercontent.com/9104198/227718524-132c7622-bb9d-49ae-93d5-7ddf624d5b48.png)
It looks like its now missing data from sundays, the others seem about right. Could you take another look?

**Comment by ppfeufer** [comment]
Sunday is a day off, you're not supposed to work on that day :-P

Ya, I'll have a look.
