### ISSUE TITLE
[Feature Request] Alt Char detetection

### ISSUE THREAD

**Issue by SirNomad49** [ppfeufer/allianceauth-afat#262]
### Context

Automatic FAT Tracking through ESI and manual tracking through link creation

### Describe the feature you have in mind

Acceptance Criteria: 
It would be good to have the option for Alt tracking, so that the FAT link is only counted per person and not per Character. 
This should be a configurable option, because not every alliance would like to track it per person.

### Additional context

The connect between main character and alt should already exist. 

![image](https://user-images.githubusercontent.com/5516669/232628179-9dfd7b30-24b2-409b-8aeb-28266993bc2e.png)

**Comment by ppfeufer** [comment]
Sorry, but I have to decline this one.

It's FAT (Fleet Activity Tracking), not PAT (Player Activity Tracking).

If someone puts 3 chars in the same or even different fleets during a fight, they deserve to get 3 FATs.

**Comment by SirNomad49** [comment]
Hello, that is why we would like to have it configureable. 

So that it can do both, player tracking and character tracking.
