### ISSUE TITLE
Corp Member Statistics - Blue view icon does not work

### ISSUE THREAD

**Issue by SoraTheExplorer** [ppfeufer/allianceauth-afat#378]
### Bug Description

The blue view icon does not work on the Statistics page for a corporation,

### Steps to Reproduce

1. Go to Fleet Activity Tracking
2. Click on Statistics
3. Click on Corporations
4. Click the dropdown next to an alliance
5. Click the blue icon next to a corp.
6. Choose any month.
7.  Go to the Members tab.
8. Click the blue eye icon.
9. Observe issue.

### Expected behavior

Assume it should show all FATS belong to that toon and any alts.

### Please complete the following information:

App Version: 3.5.0
Alliance Auth Version: 4.4.2
Browser and Version: Chrome // 131.0.6778.86

**Comment by ppfeufer** [comment]
As this is also something I cannot reproduce, here's what you can check:

- Hit F12 in your browser while having the "faulty" page open
- Reload the browser (CTRL + F5)
- Check if any errors come up in the debug console

#### This is how it should look like after you clicked the "Eye" icon
![image](https://github.com/user-attachments/assets/1d8f7562-de12-43cd-b541-f4dc9dc3385a)

**Comment by SoraTheExplorer** [comment]
This is working now after following your previous advice :)
