### ISSUE TITLE
Can no longer sort by FATs in corp statistics

### ISSUE THREAD

**Issue by SoraTheExplorer** [ppfeufer/allianceauth-afat#379]
### Bug Description

Can no longer sort by FATs in corp statistics

### Steps to Reproduce

1. Go to Fleet Activity Tracking
2. Click on Statistics
3. Click on Corporations
4. Click the dropdown next to an alliance
5. Click the blue icon next to a corp.
6. Choose any month.
7. Go to the Members tab.
8. Click FATs to try and sort into highest first
9. Observe issue.

### Expected behavior

Should be sortable into highest first like it was before.

### Please complete the following information:

App Version: 3.5.0
Alliance Auth Version: 4.4.2
Browser and Version: Chrome // 131.0.6778.86

**Comment by ppfeufer** [comment]
Another one I cannot reproduce, in either my dev or my live environment.

This table is by default sorted by FATs, highest to lowest, and can be sorted by character name on both directions and FATs in both directions.


#### Default
![image](https://github.com/user-attachments/assets/59f8fb8b-9df7-465a-a0c4-6bfed77f57dd)

#### FATs lowest to highest
![image](https://github.com/user-attachments/assets/74a7ed05-b1b3-4958-a196-9c78cc7b34c6)

#### Names A - Z
![image](https://github.com/user-attachments/assets/34555807-a65c-49c4-bcd6-61694bec0c06)

#### Names Z - A
![image](https://github.com/user-attachments/assets/3da5a9cf-9dda-447f-90d3-c80218207b17)




It seems you didn't run the static collection or have a cache issue with your system/browser.

Please [check here](https://github.com/ppfeufer/allianceauth-afat/issues/378#issuecomment-2508989615) for what you can do to try and debug.

**Comment by SoraTheExplorer** [comment]
We managed to fix this after following your comment, thank you.
