### ISSUE TITLE
[Feature Request] Add a way to see FATs for every toon in corp

### ISSUE THREAD

**Issue by SoraTheExplorer** [ppfeufer/allianceauth-afat#381]
### Context

This was something we could do before we upgraded to 3.5.0 and used it monthly.

### Describe the feature you have in mind

We monitor our corps fleet participation on all toons, not just those who have a FAT, could we please have a way to see the per toon totals (even if some are zero) as it helps us ensure inactive alts are removed

(The new by Main view is awesome by the way)

**Comment by ppfeufer** [comment]
Coming in the next release

**By main:**
![image](https://github.com/user-attachments/assets/2ee43c98-aaa6-4efb-a50b-f05019ff96f2)

**All characters:**
![image](https://github.com/user-attachments/assets/ea061bc7-cdb2-472d-a073-0b3c425ab83a)
