### ISSUE TITLE
ship types table

### ISSUE THREAD

**Issue by mackenziexD** [ppfeufer/allianceauth-afat#72]
for the `FAT Link Details` part it would be nice if we had a table or something that automacitcally pdated showing a table of ship and the number of them as all it does currently show the people in fleet and the ships they are in.

maybe something setout like this just let shitty lol.
![Example Image](https://image.prntscr.com/image/_StYb4GTS4WYRH1RyKPSFQ.png)

**Comment by ppfeufer** [comment]
Interesting idea, I'll keep a note on my list. Thank you!

**Comment by ppfeufer** [comment]
Delivered with v1.9.0
