### ISSUE TITLE
Technical: Replace outdated msg messages with Django message system

### ISSUE THREAD

**Issue by ErikKalkoken** [ppfeufer/allianceauth-afat#86]

**Comment by ppfeufer** [comment]
That's used by the built.in FAT system, right?

That's doing weird things from time to time ...

![image](https://user-images.githubusercontent.com/2989985/116864158-b2d53d80-ac07-11eb-8fd1-926af712190d.png)

**Comment by ErikKalkoken** [comment]
Yeah is is this code you see in all views:

```python
if "msg" in request.session:
    msg = request.session.pop("msg")
```
My guess is the FAT system was build before this was a thing in Django and they never cared to migrate it.
Now you can just use Django's message framework which is probably more stable and better tested.
